### PR TITLE
make message.id an integer

### PR DESCRIPTION
**Pull request by heavyk**
when trying to get the chrome-tabs example working, it claimed that id must be an integer.

### CODE REVIEW

**Comment by jessetane** [comment]
I thought chrome-tab was pinned to 2.1.1 which actually did what you're proposing here?

**Comment by jessetane** [comment]
I'm actively working on a new release for this library and I would prefer to stay with something other than an incrementing sequence for message ids. Also, the spec says strings should be ok, I wonder if we can use random but maybe convert to string before serializing?

**Comment by heavyk** [comment]
ah I copied the chrome-tabs example code ... I didn't see it was pinned (my mistake). chrome-tabs definitely does not work without an integer.

```js
// random string (does not work)
Math.random().toString(32).substr(2)
// random integer (does not work)
Math.floor(Math.random() * Number.MAX_SAFE_INTEGER)
// random 31 bit integer (works)
Math.floor(Math.random() * 2147483648)
```

**Comment by jessetane** [comment]
Thanks for looking into this - really busy next couple of days for me but I will get back to you as soon as I can

**Comment by jessetane** [comment]
Ok, I've release 6.0.0, want to try this again?

**Comment by jessetane** [comment]
Also maybe worth trying 32bit - 1? e.g. https://github.com/jessetane/rpc-events/blob/master/index.js#L3

**Comment by jessetane** [comment]
You should be able to put your id generation code here: https://github.com/jessetane/rpc-engine/blob/master/index.js#L46

**Comment by jessetane** [comment]
I think b36e4fc9673146a5e56efe354e5ec8c90b89262e closes this, reopen if not

**Pull request closed without merging**
